### ISSUE TITLE
p149 - error message using genes command

### ISSUE THREAD

**Issue by pedur1** [csortu/MDAuR#5]
Hello
I have just started working my way though Chapter 7 using rnaseq.R

when I get to the command on p149:
> genelist <- genes(txdb)

I get the following error message:
Error in `[[<-`(`*tmp*`, name, value = <S4 object of class "CompressedCharacterList">) : 
  2858 elements in value to replace 2326 elements

I am using  R-3.4.1 on a 64 bit machine running Windows 10

Thanks
Peter

**Comment by csortu** [comment]
Hi,
Sorry for the unforgivably late answer. Honestly, I am using actively this part of our code and I was not able to reproduce your error. Try to reinstall TxDb.Hsapiens.UCSC.hg19.knownGene package (and all its dependencies). 
These four lines of code should be able to test in a new R session if you have all the needed packages installed:
`library(TxDb.Hsapiens.UCSC.hg19.knownGene)
txdb <- TxDb.Hsapiens.UCSC.hg19.knownGene
seqlevels(txdb, force=TRUE) <- c("chr14")
genelist <- genes(txdb)
`
At this point you should have the genes on chromosome 14 listed in the genelist variable as a GRanges object.
Csaba
